#pragma once

#if TOCK_BOARD_hail == 1
#define BOOTLOADER_SELECT_PIN PIN_PA08

#define BOOTLOADER_UART_TX_PIN PIN_PA12A_USART0_TXD
#define BOOTLOADER_UART_TX_MUX MUX_PA12A_USART0_TXD
#define BOOTLOADER_UART_RX_PIN PIN_PA11A_USART0_RXD
#define BOOTLOADER_UART_RX_MUX MUX_PA11A_USART0_RXD
#define BOOTLOADER_UART USART0

#elif TOCK_BOARD_justjump == 1

// unused, but defined for compilation
#define BOOTLOADER_UART_TX_PIN PIN_PA12A_USART0_TXD
#define BOOTLOADER_UART_TX_MUX MUX_PA12A_USART0_TXD
#define BOOTLOADER_UART_RX_PIN PIN_PA11A_USART0_RXD
#define BOOTLOADER_UART_RX_MUX MUX_PA11A_USART0_RXD
#define BOOTLOADER_UART USART0

#else
#error "No TOCK_BOARD defined!"
#endif

